services:
  cue_postgres:
    image: postgres:alpine
    container_name: cue_postgres
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5432:5432
    volumes:
      - cue_postgres_data:/var/lib/postgresql/data

networks:
  default:
    name: cue

volumes:
  cue_postgres_data:
